
INSERT INTO `subgroupscie10` (`id`, `clave`, `descripcion`, `idGrupo`) VALUES
(1, '|I1', 'Enfermedades infecciosas intestinales', 1),
(2, '|I10', 'Fiebres virales trasmitidas por artrópodos y fiebres virales hemorrágicas', 1),
(3, '|I11', 'Infecciones virales caracterizadas por lesiones de la piel y de las membranas mucosas', 1),
(4, '|I12', 'Hepatitis viral', 1),
(5, '|I13', 'Enfermedad por virus de la inmunodeficiencia humana (HIV)', 1),
(6, '|I14', 'Otras enfermedades virales', 1),
(7, '|I15', 'Micosis', 1),
(8, '|I16', 'Enfermedades debidas a protozoarios', 1),
(9, '|I17', 'Helmintiasis', 1),
(10, '|I18', 'Pediculosis. Acariasis y otras manifestaciones', 1),
(11, '|I19', 'Secuelas de enfermedades infecciosas y parasitarias', 1),
(12, '|I20', 'Bacterias, virus y otros agentes infecciosos', 1),
(13, '|I21', 'Otras enfermedades infecciosas', 1),
(14, '|I3', 'Ciertas zoonosis bacterianas', 1),
(15, '|I4', 'Otras enfermedades bacterianas', 1),
(16, '|I5', 'Infecciones con modo de transmisión predominantemente sexual', 1),
(17, '|I6', 'Otras enfermedades debidas a espiroquetas', 1),
(18, '|I7', 'Otras enfermedades causadas por clamidias', 1),
(19, '|I8', 'Rickettsiosis', 1),
(32, '|I2', 'Tuberculosis', 2),
(33, '|II1', 'Tumores malignos de labio de la cavidad bucal y de la faringe', 2),
(34, '|II10', 'Tumores malignos de las vías urinarias', 2),
(35, '|II11', 'Tumores malignos del ojo del encéfalo y de otras partes del sistema nervioso', 2),
(36, '|II12', 'Tumores malignos de la glándula tiroides y de otras glándulas endocrinas', 2),
(37, '|II13', 'Tumores malignos de sitios mal definidos secundarios y de sitios no especificados', 2),
(38, '|II14', 'Tumores malignos del tejido linfático, de los órganos hematopoyéticos y de tejidos afines', 2),
(39, '|II15', 'Tumores malignos(primarios) de sitios múltiples independientes', 2),
(40, '|II16', 'Tumores (neoplasias) in situ', 2),
(41, '|II17', 'Tumores (neoplasias) benignos', 2),
(42, '|II18', 'Tumores (neoplasias) de comportamiento incierto o desconocido', 2),
(43, '|II2', 'Tumores malignos de los órganos digestivos', 2),
(44, '|II3', 'Tumores malignos de los órganos respiratorios e intratorácicos', 2),
(45, '|II4', 'Tumores malignos de los huesos y de los cartílagos articulares', 2),
(46, '|II5', 'Melanoma y otros tumores malignos de la piel', 2),
(47, '|II6', 'Tumores malignos de los tejidos mesoteliales y de los tejidos blandos', 2),
(48, '|II7', 'Tumor maligno de mama', 2),
(49, '|II8', 'Tumores malignos de los órganos genitales femeninos', 2),
(50, '|II9', 'Tumores malignos de los órganos genitales masculinos', 2),
(63, '|III1', 'Anemias nutricionales', 3),
(64, '|III2', 'Anemias hemolíticas', 3),
(65, '|III3', 'Anemias aplásticas y otras anemias', 3),
(66, '|III4', 'Defectos de la coagulación, púrpura y otras afecciones hemorrágicas', 3),
(67, '|III5', 'Otras enfermedades de la sangre y de los órganos hematopoyeticos', 3),
(68, '|III6', 'Ciertos trastornos que afectan el mecanismo de la inmunidad', 3),
(70, '|IV1', 'Trastornos de la glándula tiroides', 4),
(71, '|IV2', 'Diabetes mellitus', 4),
(72, '|IV3', 'Otros trastornos de la regulación de la glucosa y de la secreción interna del páncreas', 4),
(73, '|IV4', 'Trastornos de otras glándulas endocrinas.', 4),
(74, '|IV5', 'Desnutrición', 4),
(75, '|IV6', 'Otras deficiencias nutricionales', 4),
(76, '|IV7', 'Obesidad y otros tipo de hiperalimentación', 4),
(77, '|IV8', 'Trastornos metabólicos', 4),
(85, '|V1', 'Trastornos mentales orgánicos, incluidos los trastornos sintomáticos', 5),
(86, '|V10', 'Trastorno mental no especificado', 5),
(87, '|v2', 'Esquizofrenia,trastornos esquizotípicos y trastornos delirantes', 5),
(88, '|V3', 'Trastornos del humor (afectivos)', 5),
(89, '|V4', 'Trastornos neuróticos, trastornos relacionados con el stress y trastornos somatomorfos', 5),
(90, '|V5', 'Síndromes del comportamiento asociados con alteraciones fisiológicas y factores físicos', 5),
(91, '|V6', 'Trastornos de la personalidad y del comportamiento en adultos', 5),
(92, '|V7', 'Retraso mental', 5),
(93, '|V8', 'Trastornos del desarrollo psicológico', 5),
(94, '|V9', 'Trastornos emocionales y del comportamiento que aparecen habitualmente en la niñez u en la adolescencia', 5),
(100, '|VI1', 'Enfermedades inflamatorias del sistema nervioso central', 6),
(101, '|VI10', 'Parálisis cerebral y otros síndromes paralíticos', 6),
(102, '|VI11', 'Otros trastornos del sistema nervioso', 6),
(103, '|VI2', 'Atrofias sistémicas que afectan principalmente el sistema nervioso central', 6),
(104, '|VI3', 'Trastornos extrapiramidales y del movimiento', 6),
(105, '|VI4', 'Otras enfermedades degenerativas del sistema nervioso', 6),
(106, '|VI5', 'Enfermedades desmielinizantes del sistema nervioso central', 6),
(107, '|VI6', 'Trastornos episódicos y paroxístico', 6),
(108, '|VI7', 'Trastorno de los nervios,de las raíces y de los plexos nerviosos', 6),
(109, '|VI8', 'Polineuropatías y otros trastornos del sistema nervioso periférico', 6),
(110, '|VI9', 'Enfermedades musculares y de la unión neuromuscular', 6),
(115, '|VII1', 'Trastornos del párpado, aparato lagrimal y órbita', 7),
(116, '|VII10', 'Alteración de la visión y ceguera', 7),
(117, '|VII11', 'Otros trastornos del ojo y sus anexos', 7),
(118, '|VII2', 'Trastornos de la conjuntiva', 7),
(119, '|VII3', 'Trastornos de la esclerótica, córnea, iris y cuerpo ciliar', 7),
(120, '|VII4', 'Trastornos del cristalino', 7),
(121, '|VII5', 'Trastornos de la coroides y retina', 7),
(122, '|VII6', 'Glaucoma', 7),
(123, '|VII7', 'Trastornos del cuerpo vitreo y del globo ocular', 7),
(124, '|VII8', 'Trastornos del nervio óptico y de las vías ópticas', 7),
(125, '|VII9', 'Trastornos de los músculos oculares del movimiento binocular de la acomodación y de la refracción', 7),
(130, '|VIII1', 'Enfermedades del oído externo', 8),
(131, '|VIII2', 'Enfermedades del oído medio y de la mastoides', 8),
(132, '|VIII3', 'Enfermedades del oído interno', 8),
(133, '|VIII4', 'Otros trastornos del oído', 8),
(137, '|I9', 'Infecciones virales del sistema nervioso central', 9),
(138, '|IX1', 'Fiebre reumática aguda', 9),
(139, '|IX10', 'Otros trastornos y los no especificados del sistema circulatorio', 9),
(140, '|IX2', 'Enfermedades cardíacas reumáticas crónicas', 9),
(141, '|IX3', 'Enfermedades hipertensivas', 9),
(142, '|IX4', 'Enfermedades isquémicas del corazón', 9),
(143, '|IX5', 'Enfermedad cardiopulmonar y enfermedades de la circulación pulmonar', 9),
(144, '|IX6', 'Otras formas de enfermedad del corazón', 9),
(145, '|IX7', 'Enfermedades cerebrovasculares', 9),
(146, '|IX8', 'Enfermedades de las arterias, de las arteriales y de los vasos capilares', 9),
(147, '|IX9', 'Enfermedades de las venas y de los vasos y ganglios linfáticos, no clasificados en otra parte', 9),
(152, '|X1', 'Infecciones agudas de las vías respiratorias superiores', 10),
(153, '|X2', 'Influenza (gripe) y neumonía', 10),
(154, '|X3', 'Otras infecciones agudas de las vías respiratorias inferiores', 10),
(155, '|X4', 'Otras enfermedades de las vías respiratorias superiores', 10),
(156, '|X5', 'Enfermedades crónicas de las vías respiratorias inferiores', 10),
(157, '|X6', 'Enfermedades del pulmón debida a agentes externos', 10),
(158, '|X7', 'Otras enfermedades respiratorias que afectan principalmente al intersticio', 10),
(159, '|X8', 'Afecciones supurativas y necróticas de las vías respiratorias inferiores', 10),
(160, '|X9', 'Otras enfermedades de la pleura', 10),
(167, '|X10', 'Otras enfermedades del sistema respiratorio', 11),
(168, '|XI1', 'Enfermedades de la cavidad bucal de las glándulas salivales y de los maxilares', 11),
(169, '|XI10', 'Otras enfermedades del sistema digestivo', 11),
(170, '|XI2', 'Enfermedades del esófago, del estómago y del duodeno', 11),
(171, '|XI3', 'Enfermedades del apéndice', 11),
(172, '|XI4', 'Hernia', 11),
(173, '|XI5', 'Enteritis y colitis no infecciosa', 11),
(174, '|XI6', 'Otras enfermedades de los intestinos', 11),
(175, '|XI7', 'Enfermedades del peritoneo', 11),
(176, '|XI8', 'Enfermedades del hígado', 11),
(177, '|XI9', 'Trastornos de la vesícula biliar, de las vías biliares del páncreas', 11),
(182, '|XII1', 'Infecciones de la piel y del tejido subcutáneo', 12),
(183, '|XII2', 'Dermatitis y eczema', 12),
(184, '|XII3', 'Trastornos papuloescamosos', 12),
(185, '|XII4', 'Urticaria y eritema', 12),
(186, '|XII5', 'Trastornos de la piel y del tejido subcutáneo relacionados con radiación', 12),
(187, '|XII6', 'Trastornos de las faneras', 12),
(188, '|XII7', 'Otros trastornos de la piel y del tejido subcutáneo', 12),
(189, '|XIII1', 'Artropatías infecciosas', 13),
(190, '|XIII10', 'Otros trastornos de los tejidos blandos', 13),
(191, '|XIII11', 'Trastornos de la densidad y de la estructura óseas', 13),
(192, '|XIII12', 'Otras osteopatías', 13),
(193, '|XIII13', 'Condropatías', 13),
(194, '|XIII14', 'Otros trastornos del sistema osteomuscular y del tejido conjuntivo', 13),
(195, '|XIII2', 'Artrosis', 13),
(196, '|XIII3', 'Otros trastornos articulares', 13),
(197, '|XIII4', 'Trastornos sistémicos del tejido conjuntivo', 13),
(198, '|XIII5', 'Dorsopatías deformantes', 13),
(199, '|XIII6', 'Espondilopatías', 13),
(200, '|XIII7', 'Otras dorsopatias', 13),
(201, '|XIII8', 'Trastornos de los músculos', 13),
(202, '|XIII9', 'Trastornos de los tendones y de la sinovial', 13),
(204, '|XIV1', 'Enfermedades glomerulares', 14),
(205, '|XIV10', 'Trastornos no inflamatorios de los órganos pélvicos femeninos', 14),
(206, '|XIV11', 'Otros trastornos del sistema genitourinario', 14),
(207, '|XIV2', 'Enfermedad renal tubulointersticial', 14),
(208, '|XIV3', 'Insuficiencia renal', 14),
(209, '|XIV4', 'Litiasis urinaria', 14),
(210, '|XIV5', 'Otros trastornos del riñon y del uréter', 14),
(211, '|XIV6', 'Otras enfermedades del sistema urinario', 14),
(212, '|XIV7', 'Enfermedades de los órganos genitales masculinos', 14),
(213, '|XIV8', 'Trastornos de la mama', 14),
(214, '|XIV9', 'Enfermedades inflamatorias de los órganos pélvicos femeninos', 14),
(219, '|XV1', 'Embarazo terminado en aborto', 15),
(220, '|XV2', 'Edema, proteinuria y trastornos hipertensivos en el embarazo, el parto y el puerperio', 15),
(221, '|XV3', 'Otros trastornos maternos relacionados principalmente con el embarazo', 15),
(222, '|XV4', 'Atención materna relacionada con el feto y la cavidad amniótica y con posibles problemas del parto', 15),
(223, '|XV5', 'Complicaciones del trabajo de parto y del parto', 15),
(224, '|XV6', 'Parto', 15),
(225, '|XV7', 'Complicaciones principalmente relacionadas con el puerperio', 15),
(226, '|XV8', 'Otras afecciones obstétricas no clasificadas en otra parte', 15),
(227, '|XVI8', 'Trastornos del sistema digestivo del feto y del recién nacido', 15),
(228, '|XVI9', 'Afecciones asociadas con la regulación tegumentaria y la temperatura del feto y del recién nacido', 15),
(234, '|XVI1', 'Feto y recién nacido afectados por factores maternos y por complicaciones del embarazo trabajo de parto y del parto', 16),
(235, '|XVI10', 'Otros trastornos originados en el período perinatal', 16),
(236, '|XVI2', 'Trastornos relacionados con la duración de la gestación y el crecimiento fetal', 16),
(237, '|XVI3', 'Traumatismo del nacimiento', 16),
(238, '|XVI4', 'Trastornos respiratorios y cardiovasculares específicos del período perinatal', 16),
(239, '|XVI5', 'Infecciones específicas del período perinatral', 16),
(240, '|XVI6', 'Trastornos hemorrágicos y hematológicos del feto y del recién nacido', 16),
(241, '|XVI7', 'Trastornos endocrinos y metabólicos transitorios específicos del feto y del recién nacido', 16),
(249, '|XVII1', 'Malfomaciones congénitas del sistema nervioso', 17),
(250, '|XVII10', 'Otras malformaciones congénitas', 17),
(251, '|XVII11', 'Anomalías cromosómicas no clasificadas en otra parte', 17),
(252, '|XVII2', 'Malformaciones congénitas del ojo, del oído de la cara y del cuello', 17),
(253, '|XVII3', 'Malformaciones congénitas del sistema circulatorio', 17),
(254, '|XVII4', 'Malformaciones congénitas del sistema respiratorio', 17),
(255, '|XVII5', 'Fisura del paladar y labio leporino', 17),
(256, '|XVII6', 'Otras malformaciones congénitas del sistema digestivo', 17),
(257, '|XVII7', 'Malformaciones congénitas de los órganos genitales', 17),
(258, '|XVII8', 'Malformaciones congénitas del sistema urinario', 17),
(259, '|XVII9', 'Malformaciones y deformidades congénitas del sistema osteomuscular', 17),
(264, '|XVIII1', 'Síntomas y signos que involucran los sistemas circulatorios y respiratorios', 18),
(265, '|XVIII10', 'Hallazgos anormales en el examen de orina sin diagnóstico', 18),
(266, '|XVIII11', 'Hallazgos anormales en el examen de otros líquidos sustancias y tejidos corporales sin diagnóstico', 18),
(267, '|XVIII12', 'Hallazgos anormales en diagnóstico por imágenes y en estudios funcionales, sin diagnóstico', 18),
(268, '|XVIII2', 'Síntomas y signos que involucran el sistema digestivo y el abdomen', 18),
(269, '|XVIII3', 'Síntomas y signos que involucran la piel y el tejido subcutáneo', 18),
(270, '|XVIII4', 'Síntomas y signos que involucran los sistemas nervioso y osteomuscular', 18),
(271, '|XVIII5', 'Síntomas y signos que involucran el sistema urinario', 18),
(272, '|XVIII6', 'Síntomas y signos que involucran el conocimiento la percepción, el estado emocional y la conducta', 18),
(273, '|XVIII7', 'Síntomas y signos que involucran el habla y la voz', 18),
(274, '|XVIII8', 'Síntomas y signos generales', 18),
(275, '|XVIII9', 'Hallazgos anormales en el examen de sangre sin diagnóstico', 18),
(279, '|XIX1', 'Traumatismo de la cabeza', 19),
(280, '|XIX10', 'Traumatismos del tobillo y del pie', 19),
(281, '|XIX11', 'Traumatismos que afectan múltiples regiones del cuerpo', 19),
(282, '|XIX12', 'Traumatismos de parte no especificada del tronco, miembro o región del cuerpo', 19),
(283, '|XIX13', 'Efectos de cuerpos extraños que penetran por orificios naturales', 19),
(284, '|XIX14', 'Quemaduras y corrosiones de la superficie externa del cuerpo, especificadas por sitio', 19),
(285, '|XIX15', 'Quemaduras y corrosiones limitadas al ojo y órganos internos', 19),
(286, '|XIX16', 'Quemaduras y corrosiones de múltiples regiones del cuerpo y las no especificadas', 19),
(287, '|XIX17', 'Congelamiento', 19),
(288, '|XIX18', 'Envenenamiento por drogas, medicamentos y sustancias biológicas', 19),
(289, '|XIX19', 'Efectos tóxicos de sustancias de procedencia principalmente no medicinal', 19),
(290, '|XIX2', 'Traumatismos del cuello', 19),
(291, '|XIX20', 'Otros efectos y los no especificados de causas externas', 19),
(292, '|XIX21', 'Algunas complicaciones precoces de traumatismos', 19),
(293, '|XIX22', 'Complicaciones de la atención médica y quirúrgica, no clasificadas en otra parte', 19),
(294, '|XIX23', 'Secuela de traumatismos, de envenenamientos y de otras consecuencia de causa externa', 19),
(295, '|XIX3', 'Traumatismos del tórax', 19),
(296, '|XIX4', 'Traumatismos del abdomen, de la región lumbosacra de la columna lumbar y de la pelvis', 19),
(297, '|XIX5', 'Traumatismos del hombro y del brazo', 19),
(298, '|XIX6', 'Traumatismos del antebrazo y del codo', 19),
(299, '|XIX7', 'Traumatismos de la muñeca y de la mano', 19),
(300, '|XIX8', 'Traumatismos de la cadera y del muslo', 19),
(301, '|XIX9', 'Traumatismos de la rodilla y de la pierna', 19),
(310, '|XX1', 'Peatón lesionado en accidente de transporte', 20),
(311, '|XX10', 'Accidentes de transporte por agua', 20),
(312, '|XX11', 'Accidentes de transporte aéreo y espacial', 20),
(313, '|XX12', 'Otros accidentes de transporte y los no especificados', 20),
(314, '|XX13', 'Otras causas externas de traumatismos accidentales Caídas', 20),
(315, '|XX14', 'Exposición a fuerzas mecánicas inanimadas', 20),
(316, '|XX15', 'Exposición a fuerzas mecánicas animadas', 20),
(317, '|XX16', 'Ahogamiento y sumersión accidentales', 20),
(318, '|XX17', 'Otros accidentes que obstruyen la respiración', 20),
(319, '|XX18', 'Exposición a la corriente eléctrica radiación y temperatura y presión del aire ambientales extremas', 20),
(320, '|XX19', 'Exposición al fuego humo y llamas', 20),
(321, '|XX2', 'Ciclista lesionado en accidente de transporte', 20),
(322, '|XX20', 'Contacto con calor y sustancias calientes', 20),
(323, '|XX21', 'Contacto traumático con animales y plantas venenosas', 20),
(324, '|XX22', 'Exposición a fuerzas de la naturaleza', 20),
(325, '|XX23', 'Envenenamiento accidental por, y exposición a sustancias nocivas', 20),
(326, '|XX24', 'Exceso de esfuerzo, viajes y privación', 20),
(327, '|XX25', 'Exposición accidental a otros factores y a los no especificados', 20),
(328, '|XX26', 'Lesiones autoinfligidas intencionalmente', 20),
(329, '|XX27', 'Agresiones', 20),
(330, '|XX28', 'Eventos de intención no determinada', 20),
(331, '|XX29', 'Intervención legal y operaciones de guerra', 20),
(332, '|XX3', 'Motociclista lesionado en accidente de transporte', 20),
(333, '|XX30', 'Drogas medicamentos y sustancias biológicas causantes de efectos adversos en su uso terapéutico', 20),
(334, '|XX31', 'Incidentes ocurridos al paciente durante la atención médica y quirúrgica', 20),
(335, '|XX32', 'Dispositivos médicos de diagnóstico y de uso terapéutico asociados con incidentes adversos', 20),
(336, '|XX33', 'Procedimientos quirúrgicos y otros procedimientos médicos como causa de reacción anormal del paciente o complicación posterior, sin mención de incidente en el momento de efectuar el procedimiento', 20),
(337, '|XX34', 'Secuelas de causas externas de morbilidad y mortalidad', 20),
(338, '|XX35', 'Factores suplementarios relacionados con causas de morbilidad y de mortalidad clasificadas en otra parte', 20),
(339, '|XX4', 'Ocupante de vehículo de motor de tres ruedas lesionado en accidente de transporte', 20),
(340, '|XX5', 'Ocupante de automóvil lesionado en accidente de transporte', 20),
(341, '|XX6', 'Ocupante de camioneta o furgoneta lesionado en accidente de transporte', 20),
(342, '|XX7', 'Ocupante de vehículo de transporte pesado lesionado en accidente de transporte', 20),
(343, '|XX8', 'Ocupante de autobús lesionado en accidente de transporte', 20),
(344, '|XX9', 'Otros accidentes de transporte terrestre', 20),
(373, '|XXI1', 'Personas en contacto con los servicios de salud para investigación o exámenes', 21),
(374, '|XXI2', 'Personas con riesgos potenciales para su salud, relacionados con enfermedades transmisibles', 21),
(375, '|XXI3', 'Personas en contacto con los servicios de salud en circunstancias relacionadas con la reproducción', 21),
(376, '|XXI4', 'Personas en contacto con los servicios de salud para procedimientos específicos y cuidados de salud', 21),
(377, '|XXI5', 'Personas con riesgos potenciales para su salud, relacionados con circunstancias económicas y psicosociales', 21),
(378, '|XXI6', 'Personas en contacto con los servicios de salud por otras circunstancias', 21),
(379, '|XXI7', 'Personas con riesgos potenciales para su salud relacionados con su historia familiar y personal y algunas condiciones que influyen en su estado de salud', 21),
(380, '|XXII', 'Codigos para situaciones especiales', 22);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `subgroupscie10`
--
ALTER TABLE `subgroupscie10`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_gruposCie10` (`idGrupo`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `subgroupscie10`
--
ALTER TABLE `subgroupscie10`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=381;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `subgroupscie10`
--
ALTER TABLE `subgroupscie10`
  ADD CONSTRAINT `fk_groupscie10` FOREIGN KEY (`idGrupo`) REFERENCES `groupscie10` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
